# try exception

## define exception
```cpp
#include <iostream>

// Define a custom exception class
class MyException : public std::exception {
public:
    virtual const char* what() const noexcept {
        return "Custom Exception: Something went wrong!";
    }
};

int main() {
    try {
        int numerator = 10;
        int denominator = 0;

        if (denominator == 0) {
            throw MyException(); // Throwing a custom exception
        }

        int result = numerator / denominator;

        std::cout << "Result: " << result << std::endl;
    } catch (const MyException& e) {
        std::cerr << "Caught an exception: " << e.what() << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Caught a standard exception: " << e.what() << std::endl;
    }

    return 0;
}
```
output
```
Caught an exception: Custom Exception: Something went wrong!
```
